openapi: 3.0.2
info:
  contact:
    name: FED API Support
    url: https://github.com/moov-io/fed
  description: FED API is designed to create FEDACH and FEDWIRE dictionaries.  The FEDACH dictionary contains receiving depository financial institutions (RDFI’s) which are qualified to receive ACH entries.  The FEDWIRE dictionary contains receiving depository financial institutions (RDFI’s) which are qualified to receive WIRE entries.  This project implements a modern REST HTTP API for FEDACH Dictionary and FEDWIRE Dictionary.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: FED API
  version: v1
servers:
- description: Local development
  url: http://localhost:8086
tags:
- description: FEDACH Dictionary and FEDWIRE Dictionary
  name: FED
paths:
  /ping:
    get:
      operationId: ping
      responses:
        200:
          content:
            text/plain:
              example: PONG
          description: Service is running properly
      summary: Ping the FED service to check if running
      tags:
      - FED
  /fed/ach/search:
    get:
      operationId: searchFEDACH
      parameters:
      - description: Optional Request ID allows application developer to trace requests through the systems logs
        explode: false
        in: header
        name: X-Request-Id
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: FEDACH Financial Institution Name
        explode: true
        in: query
        name: name
        required: false
        schema:
          example: Farmers
          type: string
        style: form
      - description: FEDACH Routing Number for a Financial Institution
        explode: true
        in: query
        name: routingNumber
        required: false
        schema:
          example: "44112187"
          type: string
        style: form
      - description: FEDACH Financial Institution State
        explode: true
        in: query
        name: state
        required: false
        schema:
          example: OH
          type: string
        style: form
      - description: FEDACH Financial Institution City
        explode: true
        in: query
        name: city
        required: false
        schema:
          example: CALDWELL
          type: string
        style: form
      - description: FEDACH Financial Institution Postal Code
        explode: true
        in: query
        name: postalCode
        required: false
        schema:
          example: "43724"
          type: string
        style: form
      - description: Maximum results returned by a search
        explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 499
          format: int32
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ACHDictionary'
          description: FEDACH Participants returned from a search
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid, check error(s).
        500:
          description: Internal error, check error(s) and report the issue.
      summary: Search FEDACH names and metadata
      tags:
      - FED
  /fed/wire/search:
    get:
      operationId: searchFEDWIRE
      parameters:
      - description: Optional Request ID allows application developer to trace requests through the systems logs
        explode: false
        in: header
        name: X-Request-Id
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: FEDWIRE Financial Institution Name
        explode: true
        in: query
        name: name
        required: false
        schema:
          example: MIDWEST
          type: string
        style: form
      - description: FEDWIRE Routing Number for a Financial Institution
        explode: true
        in: query
        name: routingNumber
        required: false
        schema:
          example: "91905114"
          type: string
        style: form
      - description: FEDWIRE Financial Institution State
        explode: true
        in: query
        name: state
        required: false
        schema:
          example: IA
          type: string
        style: form
      - description: FEDWIRE Financial Institution City
        explode: true
        in: query
        name: city
        required: false
        schema:
          example: IOWA CITY
          type: string
        style: form
      - description: Maximum results returned by a search
        explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 499
          format: int32
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WIREDictionary'
          description: FEDWIRE Participants returned from a search
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid, check error(s).
        500:
          description: Internal error, check error(s) and report the issue.
      summary: Search FEDWIRE names and metadata
      tags:
      - FED
components:
  parameters:
    requestId:
      description: Optional Request ID allows application developer to trace requests through the systems logs
      explode: false
      in: header
      name: X-Request-Id
      required: false
      schema:
        example: 94c825ee
        type: string
      style: simple
  schemas:
    ACHDictionary:
      description: Search results containing ACHDictionary of Participants
      example:
        ACHParticipants:
        - routingNumber: "044112187"
          phoneNumber: "7407325621"
          officeCode: O
          newRoutingNumber: "000000000"
          servicingFRBNumber: "041000014"
          recordTypeCode: "1"
          revised: "20190311"
          viewCode: "1"
          customerName: FARMERS & MERCHANTS BANK
          achLocation:
          - postalExtension: "0000"
            address: 430 NORTH ST
            city: CALDWELL
            postalCode: "43724"
            state: OH
          - postalExtension: "0000"
            address: 430 NORTH ST
            city: CALDWELL
            postalCode: "43724"
            state: OH
          statusCode: "1"
        - routingNumber: "044112187"
          phoneNumber: "7407325621"
          officeCode: O
          newRoutingNumber: "000000000"
          servicingFRBNumber: "041000014"
          recordTypeCode: "1"
          revised: "20190311"
          viewCode: "1"
          customerName: FARMERS & MERCHANTS BANK
          achLocation:
          - postalExtension: "0000"
            address: 430 NORTH ST
            city: CALDWELL
            postalCode: "43724"
            state: OH
          - postalExtension: "0000"
            address: 430 NORTH ST
            city: CALDWELL
            postalCode: "43724"
            state: OH
          statusCode: "1"
      properties:
        ACHParticipants:
          items:
            $ref: '#/components/schemas/ACHParticipant'
          type: array
    ACHParticipant:
      description: ACHParticipant holds a FedACH dir routing record as defined by Fed ACH Format.  https://www.frbservices.org/EPaymentsDirectory/achFormat.html
      example:
        routingNumber: "044112187"
        phoneNumber: "7407325621"
        officeCode: O
        newRoutingNumber: "000000000"
        servicingFRBNumber: "041000014"
        recordTypeCode: "1"
        revised: "20190311"
        viewCode: "1"
        customerName: FARMERS & MERCHANTS BANK
        achLocation:
        - postalExtension: "0000"
          address: 430 NORTH ST
          city: CALDWELL
          postalCode: "43724"
          state: OH
        - postalExtension: "0000"
          address: 430 NORTH ST
          city: CALDWELL
          postalCode: "43724"
          state: OH
        statusCode: "1"
      properties:
        routingNumber:
          description: The institution's routing number
          example: "044112187"
          maxLength: 9
          minLength: 9
          type: string
        officeCode:
          description: |
            Main/Head Office or Branch

            * `O` - Main
            * `B` - Branch
          enum:
          - O
          - B
          example: O
          maxLength: 1
          minLength: 1
          type: string
        servicingFRBNumber:
          description: Servicing Fed's main office routing number
          example: "041000014"
          maxLength: 9
          minLength: 9
          type: string
        recordTypeCode:
          description: |
            The code indicating the ABA number to be used to route or send ACH items to the RDFI

            * `0` - Institution is a Federal Reserve Bank
            * `1` - Send items to customer routing number
            * `2` - Send items to customer using new routing number field
          enum:
          - "0"
          - "1"
          - "2"
          example: "1"
          maxLength: 1
          minLength: 1
          type: string
        revised:
          description: |
            Date of last revision

            * YYYYMMDD
            * Blank
          example: "20190311"
          maxLength: 8
          type: string
        newRoutingNumber:
          description: Financial Institution's new routing number resulting from a merger or renumber
          example: "000000000"
          maxLength: 9
          minLength: 9
          type: string
        customerName:
          description: Financial Institution Name
          example: FARMERS & MERCHANTS BANK
          maxLength: 36
          type: string
        achLocation:
          description: FEDACH delivery address
          items:
            $ref: '#/components/schemas/ACHLocation'
          type: array
        phoneNumber:
          description: The Financial Institution's phone number
          example: "7407325621"
          maxLength: 10
          minLength: 10
          type: string
        statusCode:
          description: |
            Code is based on the customers receiver code

            * `1` - Receives Gov/Comm
          enum:
          - "1"
          example: "1"
          maxLength: 1
          minLength: 1
          type: string
        viewCode:
          description: |-
            Code is current view

            * `1` - Current view
          enum:
          - "1"
          example: "1"
          maxLength: 1
          minLength: 1
          type: string
    ACHLocation:
      description: ACHLocation is the FEDACH delivery address
      example:
        postalExtension: "0000"
        address: 430 NORTH ST
        city: CALDWELL
        postalCode: "43724"
        state: OH
      properties:
        address:
          description: Street Address
          example: 430 NORTH ST
          maxLength: 36
          type: string
        city:
          description: City
          example: CALDWELL
          maxLength: 20
          type: string
        state:
          description: State
          example: OH
          maxLength: 2
          minLength: 2
          type: string
        postalCode:
          description: Postal Code
          example: "43724"
          maxLength: 5
          minLength: 5
          type: string
        postalExtension:
          description: Postal Code Extension
          example: "0000"
          maxLength: 4
          minLength: 4
          type: string
    WIREDictionary:
      description: Search results containing WIREDictionary of Participants
      example:
        WIREParticipants:
        - date: "20190401"
          routingNumber: "091905114"
          wireLocation:
          - city: IOWA CITY
            state: IA
          - city: IOWA CITY
            state: IA
          fundsTransferStatus: Y
          fundsSettlementOnlyStatus: S
          telegraphicName: MIDWESTONE B&T
          customerName: MIDWESTONE BK
          bookEntrySecuritiesTransferStatus: N
        - date: "20190401"
          routingNumber: "091905114"
          wireLocation:
          - city: IOWA CITY
            state: IA
          - city: IOWA CITY
            state: IA
          fundsTransferStatus: Y
          fundsSettlementOnlyStatus: S
          telegraphicName: MIDWESTONE B&T
          customerName: MIDWESTONE BK
          bookEntrySecuritiesTransferStatus: N
      properties:
        WIREParticipants:
          items:
            $ref: '#/components/schemas/WIREParticipant'
          type: array
    WIREParticipant:
      description: WIREParticipant holds a FedWIRE dir routing record as defined by Fed WIRE Format.  https://frbservices.org/EPaymentsDirectory/fedwireFormat.html
      example:
        date: "20190401"
        routingNumber: "091905114"
        wireLocation:
        - city: IOWA CITY
          state: IA
        - city: IOWA CITY
          state: IA
        fundsTransferStatus: Y
        fundsSettlementOnlyStatus: S
        telegraphicName: MIDWESTONE B&T
        customerName: MIDWESTONE BK
        bookEntrySecuritiesTransferStatus: N
      properties:
        routingNumber:
          description: The institution's routing number
          example: "091905114"
          maxLength: 9
          minLength: 9
          type: string
        telegraphicName:
          description: Short name of financial institution
          example: MIDWESTONE B&T
          maxLength: 18
          type: string
        customerName:
          description: Financial Institution Name
          example: MIDWESTONE BK
          maxLength: 36
          type: string
        wireLocation:
          description: FEDWIRE Delivery Address
          items:
            $ref: '#/components/schemas/WIRELocation'
          type: array
        fundsTransferStatus:
          description: |
            Designates funds transfer status

            * `Y` - Eligible
            * `N` - Ineligible
          enum:
          - Y
          - N
          example: Y
          maxLength: 1
          minLength: 1
          type: string
        fundsSettlementOnlyStatus:
          description: |
            Designates funds settlement only status

             * `S` - Settlement-Only
          enum:
          - S
          maxLength: 1
          type: string
        bookEntrySecuritiesTransferStatus:
          description: |
            Designates book entry securities transfer status

            * `Y` - Eligible
            * `N` - Ineligible
          enum:
          - Y
          - N
          example: N
          maxLength: 1
          minLength: 1
          type: string
        date:
          description: |
            Date of last revision

            * YYYYMMDD
            * Blank
          example: "20190401"
          maxLength: 8
          type: string
    WIRELocation:
      description: WIRELocation is the FEDWIRE delivery address
      example:
        city: IOWA CITY
        state: IA
      properties:
        city:
          description: City
          example: IOWA CITY
          maxLength: 25
          type: string
        state:
          description: State
          example: IA
          maxLength: 2
          minLength: 2
          type: string
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
          type: string
      required:
      - error
